### PR TITLE
Fix AudioButton not being imported

### LINKED ISSUE #1: No audio file working at the model viewer
Basic information

Title

Provide a clear and concise title that summarizes the issue for effective ticket handling.
No audio file working at the model viewer

Description

Start by briefly outlining the problem. Clearly state your expectations and describe the actual outcome. Be specific and avoid unnecessary details.
I could create in Lumi an additional hotspot at the provided model of the "audio" type. I could also upload 2 audio files. But if I click on the hotspot, nothing happens - no audio file to be heard. I tried it several times with different audio files, but the result was always the same.

Steps to Reproduce

Clearly outline the steps that lead to the bug. Provide a step-by-step guide for developers to reproduce the problem, including any relevant settings or configurations.

Clearly state your expected result (at each step) and contrast it with the actual result. This may not be necessary for routine steps (e.g., filling in the title field of a content type-unless there's something wrong with that, of course), but include it when there's a problem. This approach helps developers quickly identify deviations from expected behavior.

Example

Create a Question Set (1.20.12) content with a True False (1.8.x) question.
Disable the “Retry” option either in the behavioral settings of the Question Set or in the behavioral settings of the True False question.
Save the content.
Start the Question Set, navigate to the True False question and hit the “Check” button without selecting “true” or “false” as the answer option of the True False question.

Result: One is stuck and cannot finish the Question Set, because the “Finish” button does not pop up.

Expected behavior: The “Finish” button appears in order to finish the Question Set.
Create another hotspot (is that the right word?) as an "audio" type
Upload audio file
"done"
Go to the "view"
Click on the hotspot
Environment Details

H5P Content Type Name (or part of H5P)

It's important to use the correct English name. To avoid misunderstandings, cross-reference the original English content type name at https://h5p.org/content-types-and-applications.
Model Viewer

Browser

Please state the browser name (e,g, Chrome, Firefox or Safari) and also state the version number unless it's a problem on the server-side only. There typically is a menu/settings item named "Help" or "About" that will reveal the version number to you.
Lumi

H5P Integration

Please specify what H5P integration you are using. If you have administrative access, please also determine the version number.
Lumi
Supplements

Link to screenshot or screen recording (1)
https://pasteboard.co/dFxnO9G3zGzC.jpg

Link to screenshot or screen recording (2)
https://pasteboard.co/R0G7ARjal5O6.jpg

Link to screenshot or screen recording (3)

Link to page where content is hosted online or link to H5P content file.
See attachment to the email
Additional Information

Additional Information

Include any additional details that might be relevant to understanding the bug. This could include the

date and time the issue was discovered,
recent changes to the server or platform or H5P integration or content type,
other plugins that might interfere with H5P,
…
I had followed your advice to delete Lumi and upload the newest version a few days ago

### PR DESCRIPTION
**Pull request by otacke**
When merged in, will import AudioButton to Main.js, so using hotspots with audio content works.

Fixes https://github.com/codefluegel/h5p-modelviewer/issues/1

### CODE REVIEW

File: scripts/components/Main.js [hunk 1]
```diff
@@ -6,6 +6,7 @@ import ModelViewer from './ModelViewer/ModelViewer';
 import Dialog from './Dialog/Dialog';
 import InteractionContent from './Dialog/InteractionContent';
 import ToolBar from './Toolbar/Toolbar';
+import AudioButton from './HUD/Buttons/AudioButton.js';
```
Comment (patrickfrohmann) [inline scripts/components/Main.js:9]: interesting.....how did that even work? hmm

Comment (otacke) [reply scripts/components/Main.js:9]: Dunno :-) A linter would complain at least. The issue would pass certain tests, howeverm because AudioButton might as well be defined globally. But someone trying this out should have noticed this.
